algorytmy/urls.py
from django.urls import path
from . import views

app_name = 'algorytmy'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.strona_algorytmu, name='strona_algorytmu')
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

operacje_na_ulamkach/urls.py
from django.urls import path
from . import views

app_name = 'operacje_na_ulamkach'

urlpatterns = [
    path('', views.index, name='index'),
]

pokaz_elektroniki/urls.py
from django.urls import path

app_name = 'pokaz_elektroniki'
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.strona_części_elektronicznej, name = "strona_części_elektronicznej"),
]

pola_figur/urls.py
from django.urls import path
from . import views

app_name = 'pola_figur'

urlpatterns = [
    path('', views.index, name='index'),
]

szkola/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('elektronika/', include('pokaz_elektroniki.urls', namespace='pokaz_elektroniki')),
    path('pola_figur/', include('pola_figur.urls', namespace='pola_figur')),
    path('operacje_na_ulamkach/', include('operacje_na_ulamkach.urls', namespace='operacje_na_ulamkach')),
    path('algorytmy/', include('algorytmy.urls', namespace='algorytmy')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    # Serve media files in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

algorytmy/models.py
from django.db import models

class Algorytm(models.Model):

    INPUT_CHOICES = [
        ("1input", "1 input"),
        ("2inputy", "2 inputy"),
        ("3inputy", "3 inputy"),
        ("4inputy", "4 inputy"),
        ("tablica1d", "Tablica 1D"),
        ("tablica2d", "Tablica 2D"),
    ]

    nazwa = models.CharField(max_length=122)
    opis = models.TextField()
    program_java_script = models.TextField()
    program_python = models.TextField(null=True, blank=True)
    program_cpp = models.TextField(null=True, blank=True)

    typ_wejscia = models.CharField(
        max_length=20,
        choices=INPUT_CHOICES,
        default="1input"
    )

    class Meta:
        verbose_name = "Algorytm"
        verbose_name_plural = "Algorytmy"

    def __str__(self):
        return self.nazwa

operacje_na_ulamkach/models.py
from django.db import models

# Create your models here.

pokaz_elektroniki/models.py
from django.db import models

class Część_elektroniczna(models.Model):
    
    nazwa = models.CharField(max_length=30)
    opis = models.TextField()
    zdjęcie = models.ImageField(upload_to='zdjęcia')

    class Meta:
        verbose_name = "Część elektroniczna"
        verbose_name_plural = "Części elektroniczne"

algorytmy/views.py
from django.shortcuts import render, get_object_or_404
from algorytmy.models import Algorytm

def index(request):
    algorytmy =  Algorytm.objects.all()

    return render(request, 'algorytmy/index.html', {'algorytmy': algorytmy, 'active' : 'algorytmy'})


def strona_algorytmu(request, id):
    
    algorytm = get_object_or_404(Algorytm, id=id)

    return render(request, 'algorytmy/strona_algorytmu.html', {'algorytm': algorytm, 'active':'algorytmy'})

home/views.py
from django.shortcuts import render
from algorytmy.models import Algorytm

def index(request):

    algorytmy = Algorytm.objects.all()

    return render(request, 'home/index.html', {'active' : 'home', 'algorytmy':algorytmy})

operacje_na_ulamkach/views.py
from django.shortcuts import render

def index(request):

    return render(request, 'operacje_na_ulamkach/index.html', {'active' : 'operacje_na_ulamkach'})

pokaz_elektroniki/views.py
from django.shortcuts import render, get_object_or_404
from pokaz_elektroniki.models import Część_elektroniczna

def index(request):

    części_elektroniczne =  Część_elektroniczna.objects.all()

    return render(request, 'pokaz_elektroniki/index.html', {'części_elektroniczne': części_elektroniczne, 'active' : 'pokaz_elektroniki'})

def strona_części_elektronicznej(request, id):

    część = get_object_or_404(Część_elektroniczna, id=id)

    return render(request, 'pokaz_elektroniki/strona_części_elektronicznej.html', {'część' : część, 'active' : 'pokaz_elektroniki'})

pola_figur/views.py
from django.shortcuts import render

def index(request):

    return render(request, 'pola_figur/index.html', {'active' : 'pola_figur'})

algorytmy/templates/algorytmy/index.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    Algorytm
{% endblock %}

{% block content %} 
    {% for algorytm in algorytmy %}
        <a href=" {% url 'algorytmy:strona_algorytmu' algorytm.id %}" >{{ algorytm.nazwa }}</a>
    {% endfor %}
{% endblock content %}

algorytmy/templates/algorytmy/strona_algorytmu.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    {{ algorytm.nazwa }}
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs/themes/prism-okaidia.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.css">
    <script src="https://cdn.jsdelivr.net/npm/prismjs/prism.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.js"></script>
    <script>{{ algorytm.program_java_script|safe }}</script>
    
    <h1>{{ algorytm.nazwa }}</h1>
    <h3>{{ algorytm.opis }}</h3>
    <fieldset>
        {% if algorytm.typ_wejscia == "1input" %}
            <input type="number" id="input1" placeholder="input 1">
        {% elif algorytm.typ_wejscia == "2inputy" %}
            <input type="number" id="input1" placeholder="input 1">
            <input type="number" id="input2" placeholder="input 2">
        {% elif algorytm.typ_wejscia == "3inputy" %}
            <input type="number" id="input1" placeholder="input 1">
            <input type="number" id="input2" placeholder="input 2">
            <input type="number" id="input3" placeholder="input 3">
        {% elif algorytm.typ_wejscia == "4inputy" %}
            <input type="number" id="input1" placeholder="input 1">
            <input type="number" id="input2" placeholder="input 2">
            <input type="number" id="input3" placeholder="input 3">
            <input type="number" id="input4" placeholder="input 4">
        {% elif algorytm.typ_wejscia == "tablica1d" %}
            <script>
                const input_ile_p = document.getElementById("ile_p");
                input_ile_p.addEventListener("input", () => {
                    const value = input_ile_p.value;
                    const formContainer = document.getElementById(`1d`);
                    formContainer.innerHTML = "";
                    for (let t = 1; t <= value; t++) {
                        formContainer.innerHTML += `
                            <input id="input${t}" type="number" placeholder="pos ${t-1}">
                        `;
                    }
                });
            </script>
            <label for="ile_p">Ile pozycji :</label>
            <input id="ile_p" placeholder="eg. 67" type="number" min="1" step="1">
            <div id="1d"></div>
            {% elif algorytm.typ_wejscia == "tablica2d" %}
            <script>
                const input_ile_c = document.getElementById("ile_c");
                const input_ile_p1 = document.getElementById("ile_p");
                function update() {
                    const valuep = Number(input_ile_p1.value);
                    const valuec = Number(input_ile_c.value);
                    if (valuep < 1 || valuec < 1) {
                        document.getElementById("here").innerHTML = "";
                        return;
                    }
                    const formContainer = document.getElementById("here");
                    formContainer.innerHTML = "";
                    for (let i = 1; i <= valuec; i++) {
                        formContainer.innerHTML += `<div id="r${i}"></div>`;
                        const row = document.getElementById(`r${i}`);
                        for (let t = 1; t <= valuep; t++) {
                            row.innerHTML += `
                                <input id="input_${i}_${t}" type="number" placeholder="[${i-1}][${t-1}]">
                            `;
                        }
                    }
                }
                input_ile_c.addEventListener("input", update);
                input_ile_p1.addEventListener("input", update);
            </script>
            <label for="ile_c">Ile rzędów :</label>
            <input id="ile_c" placeholder="np. 67" type="number" min="1" step="1">
            <label for="ile_p">Ile pozycji :</label>
            <input id="ile_p" placeholder="np. 67" type="number" min="1" step="1">
            <div id="here"></div>
        {% endif %}
        <input type="button" id="submit" onclick="calculate()" value="Oblicz">
        <div id="answers"></div>
    </fieldset>
    <h3>Program napisany w java script</h3>
    <pre class="line-numbers"><code class="language-js">{{ algorytm.program_java_script }}</code></pre>
    {% if algorytm.program_python %}
        <h3>Program napisany w pythonie</h3>
        <pre class="line-numbers"><code class="language-python">{{ algorytm.program_python }}</code></pre>
    {% endif %}
    {% if algorytm.program_cpp %}
        <h3>Program napisany w c++</h3>
        <pre class="line-numbers"><code class="language-cpp">{{ algorytm.program_cpp }}</code></pre>
    {% endif %}
{% endblock content %}

home/templates/home/index.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %} 
    <p><a href="{% url 'pokaz_elektroniki:index' %}">Elektronika</a></p>
    <p><a href="{% url 'pola_figur:index' %}">Pola figur</a></p>
    <p><a href="{% url 'operacje_na_ulamkach:index' %}">Operacje na ulamkach</a></p>
    <p><a href="{% url 'algorytmy:index' %}">Algorytmy</a></p>
{% endblock content %}

home/templates/home/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'home/style.css' %}">

    </head>
    <body>
        <div class="topnav" id="myTopnav">
            <a href="{% url 'home:index' %}" {% if active == 'home' %}class="active"{% endif %}>Home</a>
            <a href="{% url 'pokaz_elektroniki:index' %}" {% if active == 'pokaz_elektroniki' %}class="active"{% endif %}>Elektronika</a>
            <a href="{% url 'pola_figur:index' %}" {% if active == 'pola_figur' %}class="active"{% endif %}>Pola figur</a>
            <a href="{% url 'operacje_na_ulamkach:index' %}" {% if active == 'operacje_na_ulamkach' %}class="active"{% endif %}>Operacje na ulamkach</a>
            <div class="dropdown">
                <a class="dropbtn" href="{% url 'algorytmy:index' %}" {% if active == 'algorytmy' %}class="active"{% endif %}>Algorytmy
                    <i class="fa fa-caret-down"></i>
                </a>
                <div class="dropdown-content">
                    {% for algorytm in algorytmy %}
                        <a href="{% url 'algorytmy:strona_algorytmu' algorytm.id %}">{{ algorytm.nazwa }}</a>
                    {% endfor %}
                </div>
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <div class="navbar-spacer"></div>
        {% block content %}
        {% endblock %}
        <script>
            function myFunction() {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
    </body>
</html>

operacje_na_ulamkach/templates/operacje_na_ulamkach/index.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    Operacje na ulamkach
{% endblock %}

{% block content %} 
    <script src="{% static 'operacje_na_ulamkach/script.js' %}" ></script>
    <link rel="stylesheet" href="{% static 'operacje_na_ulamkach/style.css' %}">
    <div id="container">
        <h1>Operacje na ułamkach</h1>
        <div id="sk">
            <fieldset id="skracaj">
                <legend>Skracanie</legend>
                <input type="text" id="l1"/>
                <hr></hr>
                <input type="text" id="m1"/>
                <input type="button" value="Skróć" onclick="skracjUlamek()"/>
                <p id="ulsk">Ułamek skrócony ma wartość</p>
                <input type="text" id="l1s"/>
                <hr></hr>
                <input type="text" id="m1s"/>
            </fieldset>
            <div id="dod">
                <fieldset id="dodaj">
                    <legend>Dodawanie</legend>
                    <div class="md">
                        <input type="text" id="l2"/>
                        <hr></hr>
                        <input type="text" id="m2"/>
                        <br>
                    </div>
                    <div class="md">
                        <p>+</p>
                    </div>
                    <div class="md">
                        <input type="text" id="l3">
                        <hr></hr>
                        <input type="text" id="m3">
                    </div>
                    <div class="md">
                        <p>=</p>
                    </div>
                    <div class="md">
                        <input type="text" id="lw"/>
                        <hr></hr>
                        <input type="text" id="mw"/>
                    </div>
                    <br>
                    <input type="button" value="Dodaj" onclick="dodajUlamek()"/>
                </fieldset>
            </div>
            <div id="odd">
                <fieldset id="odejmuj">
                    <legend>Dodawanie</legend>
                    <div class="md">
                        <input type="text" id="l4"/>
                        <hr></hr>
                        <input type="text" id="m4"/>
                        <br>
                    </div>
                    <div class="md">
                        <p>-</p>
                    </div>
                    <div class="md">
                        <input type="text" id="l5">
                        <hr></hr>
                        <input type="text" id="m5">
                    </div>
                    <div class="md">
                        <p>=</p>
                    </div>
                    <div class="md">
                        <input type="text" id="lw1"/>
                        <hr></hr>
                        <input type="text" id="mw1"/>
                    </div>
                    <br><br><br>
                    <input type="button" value="Odejmij" onclick="odejmijUlamek()"/>
                </fieldset>
            </div>
        </div>
    </div>
{% endblock content %}

pokaz_elektroniki/templates/pokaz_elektroniki/index.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    Pole figur
{% endblock %}

{% block content %} 
    <link rel="stylesheet" href="{% static 'pokaz_elektroniki/style.css' %}">
    <h1>Elementy elektroniczne</h1>
    <div class="image-gallery-container">
        {% for część in części_elektroniczne %}
            <div class="responsive">
                <div class="gallery">
                    {% if część.zdjęcie %}
                        <a href="{% url 'pokaz_elektroniki:strona_części_elektronicznej' część.id %}">
                            <img src="{{ część.zdjęcie.url }}" alt="{{ część.nazwa }}" class="image gallery-img">
                        </a>
                    {% else %}
                        <p>(brak zdjęcia)</p>
                    {% endif %}
                    <h4 class="desc">{{ forloop.counter }}. {{ część.nazwa }}</h4>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

pokaz_elektroniki/templates/pokaz_elektroniki/strona_części_elektronicznej.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    {{ część.nazwa }}
{% endblock %}

{% block content %} 
        <h1>{{ część.nazwa }}</h1>
        <h3>{{ część.opis }}</h3>
        {% if część.zdjęcie %}
            <img src="{{ część.zdjęcie.url }}" alt="{{ część.nazwa }}" class="image">
        {% else %}
            <p>(brak zdjęcia)</p>
        {% endif %}
        <br>
        {% if część.nazwa == "Rezystor" %}
            <a href="https://www.tiktok.com/@kelbzgoat/video/7566026034307517714?_r=1&_t=ZN-93kXUGKQLLy" target="_blank">Sigma ah edit</a>
        {% endif %}
        <a href="{% url 'pokaz_elektroniki:index' %}">link do powrotu</a>
{% endblock content %}

pola_figur/templates/pola_figur/index.html
{% extends "home/layout.html" %}
{% load static %}

{% block title %}
    Pole figur
{% endblock %}

{% block content %} 
    <script src="{% static 'pola_figur/script.js' %}" ></script>
    <link rel="stylesheet" href="{% static 'pola_figur/style.css' %}">
    <table class="centeruj">
        <tr>
            <td>
                <h2>Pole i obwód prostokąta</h2>
                <input type="number" id="rectA" placeholder="Bok a">
                <br>
                <input type="number" id="rectB" placeholder="Bok b">
                <br><button onclick="rectangle()">Oblicz</button>
                <div id="rectResult" ></div>
            </td>
            <td>
                <h2>Pole i obwód okręgu</h2>
                <input type="number" id="cirR" placeholder="Promień r">
                <br><button onclick="circle()">Oblicz</button>
                <div id="cirResult" ></div>
            </td>
        </tr>
        <tr>
            <td>
                <h2>Pole trójkąta</h2>
                <input type="number" id="trA" placeholder="Podstawa a">
                <br>
                <input type="number" id="trH" placeholder="Wysokość h">
                <br>
                <button onclick="triangleArea()">Oblicz</button>
                <div id="trAResult"></div>
            </td>
            <td>
                <h2>Pole trójkąta</h2>
                <input type="number" id="trDA" placeholder="bok a">
                <br>
                <input type="number" id="trB" placeholder="bok b">
                <br>
                <input type="number" id="trC" placeholder="bok c">
                <br>
                <button onclick="triangleDiameter()">Oblicz</button>
                <div id="trDResult"></div>
            </td>
        </tr>
        <tr>
            <td>
                <h2>Pole trapezu</h2>
                <input type="number" id="trpA" placeholder="Podstawa a">
                <br>
                <input type="number" id="trpB" placeholder="Podstawa b">
                <br>
                <input type="number" id="trpH" placeholder="Wysokość h">
                <br>
                <button onclick="trapeziumArea()">Oblicz</button>
                <div id="trpAResult"></div>
            </td>
            <td>
                <h2>Obwód trapezu</h2>
                <input type="number" id="trpDA" placeholder="bok a">
                <br>
                <input type="number" id="trpB" placeholder="bok b">
                <br>
                <input type="number" id="trpC" placeholder="bok c">
                <br>
                <input type="number" id="trpD" placeholder="bok d">
                <br>
                <button onclick="trapeziumDiameter()">Oblicz</button>
                <div id="trpDResult"></div>
            </td>
        </tr>
    </table>
{% endblock content %}